export const foundations = {
  color: {
    primary: {
      white: '#ffffff',
      black: '#000000',
    },
    gray: {
      '0': '#fcfcfd',
      '1': '#f7f8f8',
      '2': '#e9ebf0',
      '3': '#d5dadf',
      '4': '#9ba3ae',
      '5': '#7d838f',
      '6': '#5d636d',
      '7': '#343942',
      '8': '#232830',
      '9': '#171b24',
      '10': '#303136',
      '11': '#242529',
      '12': '#17181a',
      a: '#454a54',
    },
    blue: {
      '0': '#edf5ff',
      '1': '#d0e2ff',
      '2': '#a6c8ff',
      '3': '#78a9ff',
      '4': '#4589ff',
      '5': '#0f62fe',
      '6': '#0043ce',
      '7': '#002d9c',
      '8': '#001d6c',
      '9': '#011754',
      '10': '#31397d',
      '11': '#242a5c',
      '12': '#121630',
    },
    green: {
      '0': '#effff4',
      '1': '#c9f4d8',
      '2': '#96e2b0',
      '3': '#68d08c',
      '4': '#3fb768',
      '5': '#24ad53',
      '6': '#1b803e',
      '7': '#0e5b28',
      '8': '#0c3f1d',
      '9': '#003412',
      '10': '#024630',
      '11': '#013222',
      '12': '#001f15',
    },
    yellow: {
      '1': '#fff8e7',
      '2': '#fff3d7',
      '3': '#ffe7b0',
      '4': '#ffdc88',
      '5': '#ffd060',
      '6': '#ffc439',
      '7': '#ffb811',
      '8': '#d5990e',
      '9': '#aa7b0b',
      '10': '#805c09',
      '11': '#553d06',
      '12': '#2a1f03',
    },
    red: {
      '0': '#fff1f1',
      '1': '#ffd7d9',
      '2': '#ffb3b8',
      '3': '#ff8389',
      '4': '#fa4d56',
      '5': '#da1e28',
      '6': '#a2191f',
      '7': '#750e13',
      '8': '#570408',
      '9': '#420003',
      '10': '#6f1f18',
      '11': '#4e1611',
      '12': '#2f0d0a',
    },
    'black opacity': {
      '1': '#000000',
      '2': '#000000',
      '3': '#000000',
      '4': '#000000',
      '5': '#000000',
      '6': '#000000',
      '7': '#000000',
      '8': '#000000',
      '9': '#000000',
      '10': '#000000',
    },
    'white opacity': {
      '1': '#ffffff',
      '2': '#ffffff',
      '3': '#ffffff',
      '4': '#ffffff',
      '5': '#ffffff',
      '6': '#ffffff',
      '7': '#ffffff',
      '8': '#ffffff',
      '9': '#ffffff',
      '10': '#ffffff',
    },
    'opacity of black (n)': {
      '25-0.03': '#000000',
      '50-0.06': '#000000',
      '100-0.12': '#000000',
      '200-0.26': '#000000',
      '300-0.38': '#000000',
      '500-0.54': '#000000',
      '600-0.68': '#000000',
      '800-0.87': '#000000',
    },
    'opacity of white (n)': {
      '25-0.03': '#ffffff',
      '50-0.06': '#ffffff',
      '100-0.12': '#ffffff',
      '200-0.26': '#ffffff',
      '300-0.38': '#ffffff',
      '500-0.54': '#ffffff',
      '600-0.68': '#ffffff',
      '800-0.87': '#ffffff',
    },
    purple: {
      '0': '#f6f2ff',
      '1': '#e8daff',
      '2': '#d4bbff',
      '3': '#be95ff',
      '4': '#a56eff',
      '5': '#8a3ffc',
      '6': '#6929c4',
      '7': '#491d8b',
      '8': '#360f72',
      '9': '#200050',
    },
    dark: {
      '0': '#ebebec',
      '1': '#c3c4c6',
      '2': '#9a9ba1',
      '3': '#71747c',
      '4': '#54575f',
      '5': '#474a52',
      '6': '#383b43',
      '7': '#2f3137',
      '8': '#23252a',
      '9': '#1a1b1f',
    },
    'opacity of white': {
      '300-0.3': '#ffffff',
      '500-0.5': '#ffffff',
      '700-0.7': '#ffffff',
    },
    'opacity of purple': {
      '50-0.06': '#360f72',
      '100-0.12': '#360f72',
      '200-0.26': '#360f72',
      '300-0.38': '#360f72',
      '500-0.54': '#360f72',
      '800-0.87': '#491d8b',
    },
    'opacity of blue': {
      '50-0.06': '#002d9c',
      '100-0.12': '#002d9c',
      '200-0.26': '#002d9c',
      '300-0.38': '#002d9c',
      '500-0.54': '#002d9c',
    },
    accent: {
      red: '#cc0033',
      green: '#009934',
      orange: '#e07602',
      'orange-100': '#fff9f2',
      'green-100': '#effff4',
      'red-100': '#fff1f1',
    },
    orange: {
      '0': '#fff9f2',
      '1': '#fadfc3',
      '2': '#f3c087',
      '3': '#f6a851',
      '4': '#ed8c23',
      '5': '#e07602',
      '6': '#a65701',
      '7': '#8b4901',
      '8': '#673601',
      '9': '#4a2700',
    },
  },
  gradient: {
    gr: {
      g: {
        gradientType: 'linear',
        rotation: 137.78947075568445,
        stops: [
          {
            position: 0,
            color: '#3f8bfcff',
          },
          {
            position: 0.47,
            color: '#8a3ffcff',
          },
          {
            position: 1,
            color: '#fc49caff',
          },
        ],
      },
      '001': {
        gradientType: 'linear',
        rotation: 180,
        stops: [
          {
            position: 0,
            color: '#e4eeffff',
          },
          {
            position: 0,
            color: '#3e86ffff',
          },
          {
            position: 1,
            color: '#b585ffff',
          },
        ],
      },
      '002': {
        gradientType: 'angular',
        rotation: 180,
        stops: [
          {
            position: 0,
            color: '#ff0000ff',
          },
          {
            position: 0.25,
            color: '#ffe600ff',
          },
          {
            position: 0.5,
            color: '#00ff85ff',
          },
          {
            position: 0.75,
            color: '#4200ffff',
          },
          {
            position: 1,
            color: '#ff00b8ff',
          },
          {
            position: 1,
            color: '#ff00b8ff',
          },
        ],
      },
    },
  },
  font: {
    body: {
      caption: {
        fontSize: 12,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 16,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'body-02': {
        fontSize: 14,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'body-01': {
        fontSize: 16,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 24,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
    },
    heading: {
      'heading-09': {
        fontSize: 12,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 16,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-08': {
        fontSize: 14,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-07': {
        fontSize: 16,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 24,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-06': {
        fontSize: 20,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 28,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-05': {
        fontSize: 24,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 32,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-04': {
        fontSize: 28,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 36,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-03': {
        fontSize: 32,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 40,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-02': {
        fontSize: 42,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 50,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-01': {
        fontSize: 54,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 64,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
    },
  },
  effect: {
    modal: {
      '0': {
        shadowType: 'dropShadow',
        radius: 16,
        color: '#0000001f',
        offsetX: 0,
        offsetY: 4,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 4,
        color: '#0000000a',
        offsetX: 0,
        offsetY: 4,
        spread: 0,
      },
    },
    card: {
      shadowType: 'dropShadow',
      radius: 4,
      color: '#0000001f',
      offsetX: 0,
      offsetY: 1,
      spread: 0,
    },
    hover: {
      shadowType: 'dropShadow',
      radius: 16,
      color: '#0000001f',
      offsetX: 0,
      offsetY: 4,
      spread: 0,
    },
    tooltip: {
      '0': {
        shadowType: 'dropShadow',
        radius: 5,
        color: '#0000001a',
        offsetX: 0,
        offsetY: 4,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 4,
        color: '#0000001f',
        offsetX: 0,
        offsetY: 0,
        spread: 0,
      },
    },
    toast: {
      '0': {
        shadowType: 'dropShadow',
        radius: 16,
        color: '#0000001f',
        offsetX: 2,
        offsetY: 6,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 4,
        color: '#0000001a',
        offsetX: 0,
        offsetY: 0,
        spread: 0,
      },
    },
    popover: {
      '0': {
        shadowType: 'dropShadow',
        radius: 4,
        color: '#0000000f',
        offsetX: 0,
        offsetY: 4,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 10,
        color: '#0000001f',
        offsetX: 0,
        offsetY: 2,
        spread: 0,
      },
    },
    floating: {
      '0': {
        shadowType: 'dropShadow',
        radius: 20,
        color: '#00000014',
        offsetX: 2,
        offsetY: 4,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 12,
        color: '#0000001f',
        offsetX: 0,
        offsetY: 2,
        spread: 0,
      },
    },
    'border-top': {
      shadowType: 'innerShadow',
      radius: 0,
      color: '#e9eaecff',
      offsetX: 0,
      offsetY: 1,
      spread: 0,
    },
    'border-bottom': {
      shadowType: 'innerShadow',
      radius: 0,
      color: '#e9eaecff',
      offsetX: 0,
      offsetY: -1,
      spread: 0,
    },
    focus: {
      shadowType: 'dropShadow',
      radius: 0,
      color: '#000000ff',
      offsetX: 0,
      offsetY: 0,
      spread: 2,
    },
    'focus-card': {
      shadowType: 'dropShadow',
      radius: 0,
      color: '#5a69e8ff',
      offsetX: 0,
      offsetY: 0,
      spread: 4,
    },
  },
  tokens: {
    'focus white': '#ffffffff',
    color: {
      text: {
        'text-default': '#303136ff',
        'text-caption': '#6e727cff',
        'text-placeholder': '#bcbec3ff',
        'text-disabled': '#00000033',
        'text-primary': '#5a69e8ff',
        'text-critical': '#da3c30ff',
        'text-inverse-default': '#ffffffff',
        'text-inverse-caption': '#d4d6d8ff',
        'text-primary-hover': '#4453cfff',
        'text-primary-active': '#3f49a2ff',
        'text-success': '#03885eff',
        'text-warning': '#ffb811ff',
      },
      bg: {
        'bg-01': '#ffffffff',
        'bg-03': '#f7f8f8ff',
        'bg-primary': '#5a69e8ff',
        'bg-primary-hover': '#4453cfff',
        'bg-primary-active': '#3f49a2ff',
        'bg-secondary': '#43454cff',
        'bg-secondary-hover': '#303136ff',
        'bg-secondary-active': '#242529ff',
        'bg-critical-hover': '#b53227ff',
        'bg-critical': '#da3c30ff',
        'bg-critical-active': '#91281fff',
        'bg-base-light': '#f4f5f6ff',
        'bg-tertiary': '#0000000d',
        'bg-tertiary-hover': '#0000001a',
        'bg-tertiary-active': '#00000033',
        'bg-disabled': '#0000000d',
        'bg-02': '#fcfdfdff',
        'bg-success': '#03885eff',
        'bg-success-hover': '#03734fff',
        'bg-success-active': '#025a3eff',
        'bg-warning': '#ffb811ff',
        'bg-warning-hover': '#d5990eff',
        'bg-warning-active': '#aa7b0bff',
        'bg-primary-light': '#eff0fdff',
        'bg-primary-light-hover': '#e0e3faff',
        'bg-success-light': '#eaf5f2ff',
        'bg-success-light-hover': '#d1ebe3ff',
        'bg-warning-light': '#fff8e7ff',
        'bg-warning-light-hover': '#fff3d7ff',
        'bg-critical-light': '#fceeecff',
        'bg-critical-light-hover': '#fae2e0ff',
        'bg-primary-light-active': '#ccd1f8ff',
        'bg-success-light-active': '#b7e1d4ff',
        'bg-warning-light-active': '#ffe7b0ff',
        'bg-critical-light-active': '#f4c4c1ff',
        'bg-base-light-active': '#d4d6d8ff',
        'bg-base-light-hover': '#e9eaecff',
      },
      border: {
        'border-default': '#e9eaecff',
        'border-strong': '#d4d6d8ff',
        'border-disabled': '#0000000d',
        'border-primary': '#5a69e8ff',
        'border-critical': '#da3c30ff',
        'border-success-light': '#d1ebe3ff',
        'border-primary-light': '#e0e3faff',
        'border-yellow-light': '#fff3d7ff',
        'border-critical-light': '#fae2e0ff',
        'border-white': '#ffffffff',
        'border-black': '#000000ff',
      },
      icon: {
        'icon-default': '#6e727cff',
        'icon-critical': '#da3c30ff',
        'icon-inverse-default': '#d4d6d8ff',
        'icon-disabled': '#00000033',
        'icon-light': '#a3a6aeff',
        'icon-inverse-white': '#ffffffff',
        'icon-primary': '#5a69e8ff',
        'icon-success': '#03885eff',
        'icon-warning': '#ffb811ff',
      },
      specialty: {
        'tooltip-bg': '#303136ff',
        'avatar-bg': '#a3a6aeff',
        'image-on-bg': '#0000004d',
      },
    },
    radius: {
      'radius-01': 2,
      'radius-02': 4,
      'radius-03': 8,
      'radius-04': 12,
      'radius-full': 9999,
      'radius-00': 0,
    },
    border: {
      'border-01': 1,
      'border-02': 2,
      'border-03': 3,
      'border-04': 4,
    },
  },
  typography: {
    body: {
      caption: {
        fontSize: 12,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 16,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'body-02': {
        fontSize: 14,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'body-01': {
        fontSize: 16,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 24,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
    },
    heading: {
      'heading-09': {
        fontSize: 12,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 16,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-08': {
        fontSize: 14,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-07': {
        fontSize: 16,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 24,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-06': {
        fontSize: 20,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 28,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-05': {
        fontSize: 24,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 32,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-04': {
        fontSize: 28,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 36,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-03': {
        fontSize: 32,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 40,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-02': {
        fontSize: 42,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 50,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-01': {
        fontSize: 54,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 64,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
    },
  },
};
