export const foundations = {
  color: {
    white: '#ffffff',
    black: '#000000',
    light_gray: {
      '1': '#fcfdfd',
      '2': '#f9fafb',
      '3': '#f6f8f9',
      '4': '#f3f6f7',
    },
    gray: {
      '1': '#f4f5f6',
      '2': '#e9eaec',
      '3': '#d4d6d8',
      '4': '#bcbec3',
      '5': '#a3a6ae',
      '6': '#898c95',
      '7': '#6e727c',
      '8': '#5b5e67',
      '9': '#43454c',
      '10': '#303136',
      '11': '#242529',
      '12': '#17181a',
    },
    blue: {
      '1': '#eff0fd',
      '2': '#e0e3fa',
      '3': '#ccd1f8',
      '4': '#b3baf4',
      '5': '#909bf0',
      '6': '#7582ec',
      '7': '#5a69e8',
      '8': '#4453cf',
      '9': '#3f49a2',
      '10': '#31397d',
      '11': '#242a5c',
      '12': '#121630',
    },
    green: {
      '1': '#eaf5f2',
      '2': '#d1ebe3',
      '3': '#b7e1d4',
      '4': '#91d4bf',
      '5': '#56bd9d',
      '6': '#33a37f',
      '7': '#03885e',
      '8': '#03734f',
      '9': '#025a3e',
      '10': '#024630',
      '11': '#013222',
      '12': '#001f15',
    },
    yellow: {
      '1': '#fff8e7',
      '2': '#fff3d7',
      '3': '#ffe7b0',
      '4': '#ffdc88',
      '5': '#ffd060',
      '6': '#ffc439',
      '7': '#ffb811',
      '8': '#d5990e',
      '9': '#aa7b0b',
      '10': '#805c09',
      '11': '#553d06',
      '12': '#2a1f03',
    },
    red: {
      '1': '#fceeec',
      '2': '#fae2e0',
      '3': '#f4c4c1',
      '4': '#eea7a1',
      '5': '#e88880',
      '6': '#e2655b',
      '7': '#da3c30',
      '8': '#b53227',
      '9': '#91281f',
      '10': '#6f1f18',
      '11': '#4e1611',
      '12': '#2f0d0a',
    },
    black_opacity: {
      '1': '#000000',
      '2': '#000000',
      '3': '#000000',
      '4': '#000000',
      '5': '#000000',
      '6': '#000000',
      '7': '#000000',
      '8': '#000000',
      '9': '#000000',
      '10': '#000000',
    },
    white_opacity: {
      '1': '#ffffff',
      '2': '#ffffff',
      '3': '#ffffff',
      '4': '#ffffff',
      '5': '#ffffff',
      '6': '#ffffff',
      '7': '#ffffff',
      '8': '#ffffff',
      '9': '#ffffff',
      '10': '#ffffff',
    },
  },
  font: {
    body: {
      caption: {
        fontSize: 12,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 16,
      },
      body_02: {
        fontSize: 14,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
      },
      body_01: {
        fontSize: 16,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 24,
      },
    },
    heading: {
      heading_09: {
        fontSize: 12,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 16,
      },
      heading_08: {
        fontSize: 14,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
      },
      heading_07: {
        fontSize: 16,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 24,
      },
      heading_06: {
        fontSize: 20,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 28,
      },
      heading_05: {
        fontSize: 24,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 32,
      },
      heading_04: {
        fontSize: 28,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 36,
      },
      heading_03: {
        fontSize: 32,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 40,
      },
      heading_02: {
        fontSize: 42,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 50,
      },
      heading_01: {
        fontSize: 54,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 64,
      },
    },
  },
  effect: {
    modal: {
      '0': {
        shadowType: 'dropShadow',
        radius: 16,
        color: '#0000001f',
        offsetX: 0,
        offsetY: 4,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 4,
        color: '#0000000a',
        offsetX: 0,
        offsetY: 4,
        spread: 0,
      },
    },
    card: {
      shadowType: 'dropShadow',
      radius: 4,
      color: '#0000001f',
      offsetX: 0,
      offsetY: 1,
      spread: 0,
    },
    hover: {
      shadowType: 'dropShadow',
      radius: 16,
      color: '#0000001f',
      offsetX: 0,
      offsetY: 4,
      spread: 0,
    },
    tooltip: {
      '0': {
        shadowType: 'dropShadow',
        radius: 5,
        color: '#0000001a',
        offsetX: 0,
        offsetY: 4,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 4,
        color: '#0000001f',
        offsetX: 0,
        offsetY: 0,
        spread: 0,
      },
    },
    toast: {
      '0': {
        shadowType: 'dropShadow',
        radius: 16,
        color: '#0000001f',
        offsetX: 2,
        offsetY: 6,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 4,
        color: '#0000001a',
        offsetX: 0,
        offsetY: 0,
        spread: 0,
      },
    },
    popover: {
      '0': {
        shadowType: 'dropShadow',
        radius: 4,
        color: '#0000000f',
        offsetX: 0,
        offsetY: 4,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 10,
        color: '#0000001f',
        offsetX: 0,
        offsetY: 2,
        spread: 0,
      },
    },
    floating: {
      '0': {
        shadowType: 'dropShadow',
        radius: 20,
        color: '#00000014',
        offsetX: 2,
        offsetY: 4,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 12,
        color: '#0000001f',
        offsetX: 0,
        offsetY: 2,
        spread: 0,
      },
    },
    border_top: {
      shadowType: 'innerShadow',
      radius: 0,
      color: '#e9eaecff',
      offsetX: 0,
      offsetY: 1,
      spread: 0,
    },
    border_bottom: {
      shadowType: 'innerShadow',
      radius: 0,
      color: '#e9eaecff',
      offsetX: 0,
      offsetY: -1,
      spread: 0,
    },
    focus: {
      shadowType: 'dropShadow',
      radius: 0,
      color: '#000000ff',
      offsetX: 0,
      offsetY: 0,
      spread: 2,
    },
    focus_card: {
      shadowType: 'dropShadow',
      radius: 0,
      color: '#5a69e8ff',
      offsetX: 0,
      offsetY: 0,
      spread: 4,
    },
  },
  tokens: {
    color: {
      text: {
        text_default: '#303136ff',
        text_caption: '#6e727cff',
        text_placeholder: '#bcbec3ff',
        text_disabled: '#00000033',
        text_primary: '#5a69e8ff',
        text_critical: '#da3c30ff',
        text_light: '#ffffffff',
        text_inverse_caption: '#d4d6d8ff',
        text_primary_hover: '#4453cfff',
        text_primary_active: '#3f49a2ff',
        text_success: '#03885eff',
        text_warning: '#ffb811ff',
        text_dark: '#000000ff',
        text_base: '#43454cff',
        text_base_hover: '#303136ff',
        text_base_active: '#242529ff',
      },
      bg: {
        bg_surface_01: '#ffffffff',
        bg_surface_03: '#f6f8f9ff',
        bg_primary: '#5a69e8ff',
        bg_primary_hover: '#4453cfff',
        bg_primary_active: '#3f49a2ff',
        bg_secondary: '#43454cff',
        bg_secondary_hover: '#303136ff',
        bg_secondary_active: '#242529ff',
        bg_critical_hover: '#b53227ff',
        bg_critical: '#da3c30ff',
        bg_critical_active: '#91281fff',
        bg_base_light: '#f4f5f6ff',
        bg_tertiary: '#0000000d',
        bg_tertiary_hover: '#0000001a',
        bg_tertiary_active: '#00000033',
        bg_disabled: '#0000000d',
        bg_surface_02: '#fcfdfdff',
        bg_success: '#03885eff',
        bg_success_hover: '#03734fff',
        bg_success_active: '#025a3eff',
        bg_warning: '#ffb811ff',
        bg_warning_hover: '#d5990eff',
        bg_warning_active: '#aa7b0bff',
        bg_primary_light: '#eff0fdff',
        bg_primary_light_hover: '#e0e3faff',
        bg_success_light: '#eaf5f2ff',
        bg_success_light_hover: '#d1ebe3ff',
        bg_warning_light: '#fff8e7ff',
        bg_warning_light_hover: '#fff3d7ff',
        bg_critical_light: '#fceeecff',
        bg_critical_light_hover: '#fae2e0ff',
        bg_primary_light_active: '#ccd1f8ff',
        bg_success_light_active: '#b7e1d4ff',
        bg_warning_light_active: '#ffe7b0ff',
        bg_critical_light_active: '#f4c4c1ff',
        bg_base_light_active: '#d4d6d8ff',
        bg_base_light_hover: '#e9eaecff',
        bg_base: '#a3a6aeff',
        bg_base_hover: '#898c95ff',
        bg_base_active: '#6e727cff',
      },
      border: {
        border_default: '#e9eaecff',
        border_strong: '#d4d6d8ff',
        border_disabled: '#0000000d',
        border_primary: '#5a69e8ff',
        border_critical: '#da3c30ff',
        border_success_light: '#d1ebe3ff',
        border_primary_light: '#e0e3faff',
        border_warning_light: '#fff3d7ff',
        border_critical_light: '#fae2e0ff',
        border_light: '#ffffffff',
        border_dark: '#000000ff',
        border_ghost_light: '#0000001a',
        border_ghost: '#000000b3',
        border_primary_hover: '#4453cfff',
      },
      icon: {
        icon_default: '#6e727cff',
        icon_critical: '#da3c30ff',
        icon_inverse_default: '#d4d6d8ff',
        icon_disabled: '#00000033',
        icon_light: '#a3a6aeff',
        icon_inverse_white: '#ffffffff',
        icon_primary: '#5a69e8ff',
        icon_success: '#03885eff',
        icon_warning: '#ffb811ff',
      },
      specialty: {
        tooltip_bg: '#303136ff',
        avatar_bg: '#a3a6aeff',
        image_on_bg: '#0000004d',
      },
    },
    radius: {
      radius_01: 2,
      radius_02: 4,
      radius_03: 8,
      radius_04: 12,
      radius_full: 9999,
      radius_00: 0,
    },
    border: {
      border_01: 1,
      border_02: 2,
      border_03: 3,
      border_04: 4,
    },
    size: {
      size_01: 2,
      size_02: 4,
      size_03: 6,
      size_04: 8,
      size_06: 12,
      size_07: 16,
      size_08: 20,
      size_09: 24,
      size_11: 32,
      size_13: 40,
      size_14: 48,
      size_15: 64,
      size_16: 80,
      size_17: 96,
      size_18: 128,
      size_19: 160,
      size_12: 36,
      size_05: 10,
      size_10: 28,
    },
  },
  typography: {
    body: {
      caption: {
        fontSize: 12,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 16,
      },
      body_02: {
        fontSize: 14,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
      },
      body_01: {
        fontSize: 16,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 24,
      },
    },
    heading: {
      heading_09: {
        fontSize: 12,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 16,
      },
      heading_08: {
        fontSize: 14,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
      },
      heading_07: {
        fontSize: 16,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 24,
      },
      heading_06: {
        fontSize: 20,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 28,
      },
      heading_05: {
        fontSize: 24,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 32,
      },
      heading_04: {
        fontSize: 28,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 36,
      },
      heading_03: {
        fontSize: 32,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 40,
      },
      heading_02: {
        fontSize: 42,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 50,
      },
      heading_01: {
        fontSize: 54,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 64,
      },
    },
  },
};
