export const foundations = {
  color: {
    primary: {
      white: '#ffffff',
      black: '#000000',
    },
    gray: {
      '1': '#f4f5f6',
      '2': '#e9eaec',
      '3': '#d4d6d8',
      '4': '#bcbec3',
      '5': '#a3a6ae',
      '6': '#898c95',
      '7': '#6e727c',
      '8': '#5b5e67',
      '9': '#43454c',
      '10': '#303136',
      '11': '#242529',
      '12': '#17181a',
    },
    blue: {
      '1': '#eff0fd',
      '2': '#e0e3fa',
      '3': '#ccd1f8',
      '4': '#b3baf4',
      '5': '#909bf0',
      '6': '#7582ec',
      '7': '#5a69e8',
      '8': '#4453cf',
      '9': '#3f49a2',
      '10': '#31397d',
      '11': '#242a5c',
      '12': '#121630',
    },
    green: {
      '1': '#eaf5f2',
      '2': '#d1ebe3',
      '3': '#b7e1d4',
      '4': '#91d4bf',
      '5': '#56bd9d',
      '6': '#33a37f',
      '7': '#03885e',
      '8': '#03734f',
      '9': '#025a3e',
      '10': '#024630',
      '11': '#013222',
      '12': '#001f15',
    },
    yellow: {
      '1': '#fff8e7',
      '2': '#fff3d7',
      '3': '#ffe7b0',
      '4': '#ffdc88',
      '5': '#ffd060',
      '6': '#ffc439',
      '7': '#ffb811',
      '8': '#d5990e',
      '9': '#aa7b0b',
      '10': '#805c09',
      '11': '#553d06',
      '12': '#2a1f03',
    },
    red: {
      '1': '#fceeec',
      '2': '#fae2e0',
      '3': '#f4c4c1',
      '4': '#eea7a1',
      '5': '#e88880',
      '6': '#e2655b',
      '7': '#da3c30',
      '8': '#b53227',
      '9': '#91281f',
      '10': '#6f1f18',
      '11': '#4e1611',
      '12': '#2f0d0a',
    },
    'black opacity': {
      '1': '#000000',
      '2': '#000000',
      '3': '#000000',
      '4': '#000000',
      '5': '#000000',
      '6': '#000000',
      '7': '#000000',
      '8': '#000000',
      '9': '#000000',
      '10': '#000000',
    },
    'white opacity': {
      '1': '#ffffff',
      '2': '#ffffff',
      '3': '#ffffff',
      '4': '#ffffff',
      '5': '#ffffff',
      '6': '#ffffff',
      '7': '#ffffff',
      '8': '#ffffff',
      '9': '#ffffff',
      '10': '#ffffff',
    },
  },
  font: {
    body: {
      caption: {
        fontSize: 12,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 16,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'body-02': {
        fontSize: 14,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'body-01': {
        fontSize: 16,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 24,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
    },
    heading: {
      'heading-09': {
        fontSize: 12,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 16,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-08': {
        fontSize: 14,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-07': {
        fontSize: 16,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 24,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-06': {
        fontSize: 20,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 28,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-05': {
        fontSize: 24,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 32,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-04': {
        fontSize: 28,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 36,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-03': {
        fontSize: 32,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 40,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-02': {
        fontSize: 42,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 50,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-01': {
        fontSize: 54,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 64,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
    },
  },
  effect: {
    modal: {
      '0': {
        shadowType: 'dropShadow',
        radius: 16,
        color: '#0000001f',
        offsetX: 0,
        offsetY: 4,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 4,
        color: '#0000000a',
        offsetX: 0,
        offsetY: 4,
        spread: 0,
      },
    },
    card: {
      shadowType: 'dropShadow',
      radius: 4,
      color: '#0000001f',
      offsetX: 0,
      offsetY: 1,
      spread: 0,
    },
    hover: {
      shadowType: 'dropShadow',
      radius: 16,
      color: '#0000001f',
      offsetX: 0,
      offsetY: 4,
      spread: 0,
    },
    tooltip: {
      '0': {
        shadowType: 'dropShadow',
        radius: 5,
        color: '#0000001a',
        offsetX: 0,
        offsetY: 4,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 4,
        color: '#0000001f',
        offsetX: 0,
        offsetY: 0,
        spread: 0,
      },
    },
    toast: {
      '0': {
        shadowType: 'dropShadow',
        radius: 16,
        color: '#0000001f',
        offsetX: 2,
        offsetY: 6,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 4,
        color: '#0000001a',
        offsetX: 0,
        offsetY: 0,
        spread: 0,
      },
    },
    popover: {
      '0': {
        shadowType: 'dropShadow',
        radius: 4,
        color: '#0000000f',
        offsetX: 0,
        offsetY: 4,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 10,
        color: '#0000001f',
        offsetX: 0,
        offsetY: 2,
        spread: 0,
      },
    },
    floating: {
      '0': {
        shadowType: 'dropShadow',
        radius: 20,
        color: '#00000014',
        offsetX: 2,
        offsetY: 4,
        spread: 0,
      },
      '1': {
        shadowType: 'dropShadow',
        radius: 12,
        color: '#0000001f',
        offsetX: 0,
        offsetY: 2,
        spread: 0,
      },
    },
    'border-top': {
      shadowType: 'innerShadow',
      radius: 0,
      color: '#e9eaecff',
      offsetX: 0,
      offsetY: 1,
      spread: 0,
    },
    'border-bottom': {
      shadowType: 'innerShadow',
      radius: 0,
      color: '#e9eaecff',
      offsetX: 0,
      offsetY: -1,
      spread: 0,
    },
    focus: {
      shadowType: 'dropShadow',
      radius: 0,
      color: '#000000ff',
      offsetX: 0,
      offsetY: 0,
      spread: 2,
    },
    'focus-card': {
      shadowType: 'dropShadow',
      radius: 0,
      color: '#5a69e8ff',
      offsetX: 0,
      offsetY: 0,
      spread: 4,
    },
  },
  tokens: {
    'focus white': '#ffffffff',
    color: {
      text: {
        'text-default': '#303136ff',
        'text-caption': '#6e727cff',
        'text-placeholder': '#bcbec3ff',
        'text-disabled': '#00000033',
        'text-primary': '#5a69e8ff',
        'text-critical': '#da3c30ff',
        'text-light': '#ffffffff',
        'text-inverse-caption': '#d4d6d8ff',
        'text-primary-hover': '#4453cfff',
        'text-primary-active': '#3f49a2ff',
        'text-success': '#03885eff',
        'text-warning': '#ffb811ff',
        'text-dark': '#000000ff',
        'text-base': '#43454cff',
        'text-base-hover': '#303136ff',
        'text-base-active': '#242529ff',
      },
      bg: {
        'bg-01': '#ffffffff',
        'bg-03': '#f7f8f8ff',
        'bg-primary': '#5a69e8ff',
        'bg-primary-hover': '#4453cfff',
        'bg-primary-active': '#3f49a2ff',
        'bg-secondary': '#43454cff',
        'bg-secondary-hover': '#303136ff',
        'bg-secondary-active': '#242529ff',
        'bg-critical-hover': '#b53227ff',
        'bg-critical': '#da3c30ff',
        'bg-critical-active': '#91281fff',
        'bg-base-light': '#f4f5f6ff',
        'bg-tertiary': '#0000000d',
        'bg-tertiary-hover': '#0000001a',
        'bg-tertiary-active': '#00000033',
        'bg-disabled': '#0000000d',
        'bg-02': '#fcfdfdff',
        'bg-success': '#03885eff',
        'bg-success-hover': '#03734fff',
        'bg-success-active': '#025a3eff',
        'bg-warning': '#ffb811ff',
        'bg-warning-hover': '#d5990eff',
        'bg-warning-active': '#aa7b0bff',
        'bg-primary-light': '#eff0fdff',
        'bg-primary-light-hover': '#e0e3faff',
        'bg-success-light': '#eaf5f2ff',
        'bg-success-light-hover': '#d1ebe3ff',
        'bg-warning-light': '#fff8e7ff',
        'bg-warning-light-hover': '#fff3d7ff',
        'bg-critical-light': '#fceeecff',
        'bg-critical-light-hover': '#fae2e0ff',
        'bg-primary-light-active': '#ccd1f8ff',
        'bg-success-light-active': '#b7e1d4ff',
        'bg-warning-light-active': '#ffe7b0ff',
        'bg-critical-light-active': '#f4c4c1ff',
        'bg-base-light-active': '#d4d6d8ff',
        'bg-base-light-hover': '#e9eaecff',
        'bg-base': '#a3a6aeff',
        'bg-base-hover': '#898c95ff',
        'bg-base-active': '#6e727cff',
      },
      border: {
        'border-default': '#e9eaecff',
        'border-strong': '#d4d6d8ff',
        'border-disabled': '#0000000d',
        'border-primary': '#5a69e8ff',
        'border-critical': '#da3c30ff',
        'border-success-light': '#d1ebe3ff',
        'border-primary-light': '#e0e3faff',
        'border-warning-light': '#fff3d7ff',
        'border-critical-light': '#fae2e0ff',
        'border-light': '#ffffffff',
        'border-dark': '#000000ff',
        'border-ghost-light': '#0000001a',
        'border-ghost': '#000000b3',
        'border-primary-hover': '#4453cfff',
      },
      icon: {
        'icon-default': '#6e727cff',
        'icon-critical': '#da3c30ff',
        'icon-inverse-default': '#d4d6d8ff',
        'icon-disabled': '#00000033',
        'icon-light': '#a3a6aeff',
        'icon-inverse-white': '#ffffffff',
        'icon-primary': '#5a69e8ff',
        'icon-success': '#03885eff',
        'icon-warning': '#ffb811ff',
      },
      specialty: {
        'tooltip-bg': '#303136ff',
        'avatar-bg': '#a3a6aeff',
        'image-on-bg': '#0000004d',
      },
    },
    radius: {
      'radius-01': 2,
      'radius-02': 4,
      'radius-03': 8,
      'radius-04': 12,
      'radius-full': 9999,
      'radius-00': 0,
    },
    border: {
      'border-01': 1,
      'border-02': 2,
      'border-03': 3,
      'border-04': 4,
    },
    size: {
      'size-01': 2,
      'size-02': 4,
      'size-03': 6,
      'size-04': 8,
      'size-06': 12,
      'size-07': 16,
      'size-08': 20,
      'size-09': 24,
      'size-11': 32,
      'size-13': 40,
      'size-14': 48,
      'size-15': 64,
      'size-16': 80,
      'size-17': 96,
      'size-18': 128,
      'size-19': 160,
      'size-12': 36,
      'size-05': 10,
      'size-10': 28,
    },
  },
  typography: {
    body: {
      caption: {
        fontSize: 12,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 16,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'body-02': {
        fontSize: 14,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'body-01': {
        fontSize: 16,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 400,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 24,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
    },
    heading: {
      'heading-09': {
        fontSize: 12,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 16,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-08': {
        fontSize: 14,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 20,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-07': {
        fontSize: 16,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 24,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-06': {
        fontSize: 20,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 28,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-05': {
        fontSize: 24,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 32,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-04': {
        fontSize: 28,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 36,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-03': {
        fontSize: 32,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 40,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-02': {
        fontSize: 42,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 50,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
      'heading-01': {
        fontSize: 54,
        textDecoration: 'none',
        fontFamily: 'Poppins',
        fontWeight: 600,
        fontStyle: 'normal',
        fontStretch: 'normal',
        letterSpacing: 0,
        lineHeight: 64,
        paragraphIndent: 0,
        paragraphSpacing: 0,
        textCase: 'none',
      },
    },
  },
};
